### ISSUE TITLE
Safe issues with GHC7.0 and 7.2

### ISSUE THREAD

**Issue by phadej** [BartMassey/parseargs#5]
GHC7.0 doesn't know about `Safe`
SafeHaskell is broken GHC7.2

```
[1 of 2] Compiling System.Console.ParseArgs ( System/Console/ParseArgs.hs, dist/dist-sandbox-689addbb/build/parseargs-example/parseargs-example-tmp/System/Console/ParseArgs.o )

System/Console/ParseArgs.hs:68:1:
    containers-0.4.1.0:Data.Map can't be safely imported! The module itself isn't safe.
```

I made revisions for two latest releases on hackage, bumping `base` lower bound to restrict GHC versions

http://matrix.hackage.haskell.org/package/parseargs https://hackage.haskell.org/package/parseargs-0.2.0.4/revisions/

**Comment by BartMassey** [comment]
Thanks for the note!

I instead made Safe conditional on GHC version: does this also fix the problem? My intent is to make parseargs available to all versions of base.

Let me know if this looks right and I'll upload to Hackage. Again, thanks.

**Comment by phadej** [comment]
You could setup travis to run tests on all ghc's you plan to support: https://github.com/hvr/multi-ghc-travis

**Comment by BartMassey** [comment]
Thanks for the pointer! Done. Added a couple of very simple tests; need to add many more. I will upload to Hackage today or tomorrow when I am confident it's ready.

**Comment by BartMassey** [comment]
OK, I've uploaded https://github.com/BartMassey/parseargs/releases/tag/v0.2.0.7 . I'm closing this for now: let me know if there are further problems.
